export const pets = [
  {
    id: 1,
    nome: 'Dunga',
    idade: '2 anos',
    descricao: 'Porte pequeno, calmo e educado',
    local: 'Rio de Janeiro (RJ)',
    imagem: 'src/assets/pets/Dunga.jpg',
  },
  {
    id: 2,
    nome: 'Felícia',
    idade: '3 meses',
    descricao: 'Porte pequeno. Ativa e carinhosa',
    local: 'Nova Iguaçu (RJ)',
    imagem: 'src/assets/pets/Felicia.jpg',
  },
  {
    id: 3,
    nome: 'Sirius',
    idade: '6 meses',
    descricao: 'Porte grande, ativo e educado',
    local: 'Duque de Caxias (RJ))',
    imagem: 'src/assets/pets/Sirius.jpg',
  },
  {
    id: 4,
    nome: 'Fiona',
    idade: '3 anos',
    descricao: 'Porte pequeno, calma e carinhosa',
    local: 'São Gonçalo (RJ)',
    imagem: 'src/assets/pets/Fiona.jpg',
  },
  {
    id: 5,
    nome: 'Sid',
    idade: '8 meses',
    descricao: 'Porte médio/grande brincalhão e amável',
    local: 'Rio de Janeiro (RJ)',
    imagem: 'src/assets/pets/Sid.jpg',
  },
  {
    id: 6,
    nome: 'Yoda',
    idade: '1 ano',
    descricao: 'Porte médio, ativo e carinhoso',
    local: 'Nova Iguaçu (RJ)',
    imagem: 'src/assets/pets/Yoda.jpg',
  },
  {
    id: 7,
    nome: 'Lua',
    idade: '6 meses',
    descricao: 'Porte médio, ativa e carinhosa',
    local: 'Duque de Caxias (RJ)',
    imagem: 'src/assets/pets/Lua.jpg',
  },
  {
    id: 8,
    nome: 'Amora',
    idade: '45 dias',
    descricao: 'Porte grande, calma e carinhosa ',
    local: 'São Gonçalo (RJ)',
    imagem: 'src/assets/pets/Amora.jpg',
  },
  {
    id: 9,
    nome: 'Zelda',
    idade: '5 meses',
    descricao: 'Ativa e amável',
    local: 'Rio de Janeiro (RJ)',
    imagem: 'src/assets/pets/Zelda.jpg',
  },
];
